export const mockUser = {
  id: 1,
  name: "John Doe",
  email: "john@example.com",
  role: "Admin", // or "User"
  avatar: "/placeholder.svg?height=40&width=40",
  department: "Engineering",
  joinDate: "2023-01-15",
}

export const mockProjects = [
  {
    id: 1,
    name: "Website Redesign",
    description: "Complete overhaul of company website",
    status: "In Progress",
    progress: 65,
    dueDate: "2024-02-15",
    team: ["John Doe", "Jane Smith", "Mike Johnson"],
    tags: ["Design", "Frontend"],
    priority: "High",
  },
  {
    id: 2,
    name: "Mobile App Development",
    description: "Native iOS and Android application",
    status: "Planning",
    progress: 25,
    dueDate: "2024-04-30",
    team: ["Sarah Wilson", "Tom Brown"],
    tags: ["Mobile", "Development"],
    priority: "Medium",
  },
  {
    id: 3,
    name: "Database Migration",
    description: "Migrate from MySQL to PostgreSQL",
    status: "Completed",
    progress: 100,
    dueDate: "2024-01-20",
    team: ["Alex Chen", "Lisa Park"],
    tags: ["Backend", "Database"],
    priority: "High",
  },
]

export const mockTasks = [
  {
    id: 1,
    title: "Design homepage mockup",
    description: "Create wireframes and mockups for the new homepage design",
    status: "Backlog",
    priority: "High",
    assignee: "Jane Smith",
    project: "Website Redesign",
    dueDate: "2024-01-25",
    tags: ["Design", "UI/UX"],
    comments: 3,
    attachments: 2,
    storyPoints: 8,
  },
  {
    id: 2,
    title: "Implement user authentication",
    description: "Set up JWT-based authentication system",
    status: "Sprint Backlog",
    priority: "High",
    assignee: "John Doe",
    project: "Mobile App Development",
    dueDate: "2024-01-30",
    tags: ["Backend", "Security"],
    comments: 5,
    attachments: 1,
    storyPoints: 13,
  },
  {
    id: 3,
    title: "Write API documentation",
    description: "Document all REST API endpoints",
    status: "Done",
    priority: "Medium",
    assignee: "Mike Johnson",
    project: "Website Redesign",
    dueDate: "2024-01-20",
    tags: ["Documentation"],
    comments: 2,
    attachments: 0,
    storyPoints: 5,
  },
  {
    id: 4,
    title: "Setup CI/CD pipeline",
    description: "Configure automated testing and deployment",
    status: "Review",
    priority: "Medium",
    assignee: "Sarah Wilson",
    project: "Database Migration",
    dueDate: "2024-02-05",
    tags: ["DevOps", "Automation"],
    comments: 1,
    attachments: 3,
    storyPoints: 21,
  },
  {
    id: 5,
    title: "Create user registration flow",
    description: "Design and implement user registration with email verification",
    status: "In Progress",
    priority: "High",
    assignee: "John Doe",
    project: "Website Redesign",
    dueDate: "2024-02-10",
    tags: ["Frontend", "Backend"],
    comments: 4,
    attachments: 1,
    storyPoints: 13,
  },
  {
    id: 6,
    title: "Design mobile app icons",
    description: "Create app icons for different screen sizes and platforms",
    status: "Backlog",
    priority: "Medium",
    assignee: "Jane Smith",
    project: "Mobile App Development",
    dueDate: "2024-02-15",
    tags: ["Design", "Mobile"],
    comments: 1,
    attachments: 0,
    storyPoints: 5,
  },
  {
    id: 7,
    title: "Implement push notifications",
    description: "Add push notification functionality to mobile app",
    status: "Sprint Backlog",
    priority: "High",
    assignee: "Mike Johnson",
    project: "Mobile App Development",
    dueDate: "2024-02-20",
    tags: ["Mobile", "Backend"],
    comments: 2,
    attachments: 2,
    storyPoints: 8,
  },
  {
    id: 8,
    title: "Database performance optimization",
    description: "Optimize database queries and add indexes",
    status: "Done",
    priority: "High",
    assignee: "Sarah Wilson",
    project: "Database Migration",
    dueDate: "2024-01-18",
    tags: ["Database", "Performance"],
    comments: 3,
    attachments: 1,
    storyPoints: 13,
  },
]

export const mockTeamMembers = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    role: "Admin",
    department: "Engineering",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "online",
    tasksCount: 8,
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@example.com",
    role: "User",
    department: "Design",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "away",
    tasksCount: 5,
  },
  {
    id: 3,
    name: "Mike Johnson",
    email: "mike@example.com",
    role: "User",
    department: "Engineering",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "online",
    tasksCount: 12,
  },
  {
    id: 4,
    name: "Sarah Wilson",
    email: "sarah@example.com",
    role: "User",
    department: "Marketing",
    avatar: "/placeholder.svg?height=40&width=40",
    status: "offline",
    tasksCount: 3,
  },
]

export const mockNotifications = [
  {
    id: 1,
    title: "Task assigned to you",
    message: "You have been assigned to 'Design homepage mockup'",
    type: "assignment",
    read: false,
    timestamp: "2024-01-22T10:30:00Z",
  },
  {
    id: 2,
    title: "Project deadline approaching",
    message: "Website Redesign project is due in 3 days",
    type: "deadline",
    read: false,
    timestamp: "2024-01-22T09:15:00Z",
  },
  {
    id: 3,
    title: "Comment on your task",
    message: "Jane Smith commented on 'Implement user authentication'",
    type: "comment",
    read: true,
    timestamp: "2024-01-21T16:45:00Z",
  },
]

export const mockCalendarEvents = [
  {
    id: 1,
    title: "Sprint Planning",
    date: "2024-01-25",
    time: "09:00",
    type: "meeting",
    project: "Website Redesign",
  },
  {
    id: 2,
    title: "Design Review",
    date: "2024-01-26",
    time: "14:00",
    type: "review",
    project: "Mobile App Development",
  },
  {
    id: 3,
    title: "Homepage Mockup Due",
    date: "2024-01-25",
    time: "17:00",
    type: "deadline",
    project: "Website Redesign",
  },
]
